// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhZcXbJa76nAt_nuWtP3YKZtu_tElGv9k',
    appId: '1:663354311647:android:746b1a9c15d9158640ba6a',
    messagingSenderId: '663354311647',
    projectId: 'devshabitat',
    storageBucket: 'devshabitat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVbwjUoiKllxHDea7mJuBw4RAJylLi0UI',
    appId: '1:663354311647:ios:bc7984af4ca4590c40ba6a',
    messagingSenderId: '663354311647',
    projectId: 'devshabitat',
    storageBucket: 'devshabitat.firebasestorage.app',
    androidClientId:
        '663354311647-ca64iiag11lipn1na55m9abhnbvehrk1.apps.googleusercontent.com',
    iosClientId:
        '663354311647-b08kjil14ms6a2bqlul9o0r54ocb90jh.apps.googleusercontent.com',
    iosBundleId: 'site.tunckankilic.devshabitat',
  );
}
