name: devshabitat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.9.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.6.11
  connectivity_plus: ^6.1.4
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.5.0
  encrypt: ^5.0.3
  file_picker: ^10.2.0
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_storage: ^12.4.9
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_slidable: ^4.0.0
  flutter_highlight: ^0.7.0
  geolocator: ^9.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^7.1.0
  http: ^1.2.0
  image: ^4.1.3
  image_cropper: ^9.1.0
  image_picker: ^1.0.5
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  oauth2: ^2.0.2
  path: ^1.8.3
  path_provider: ^2.1.2
  photo_view: ^0.15.0
  share_plus: ^11.0.0
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^7.0.1
  table_calendar: ^3.0.9
  timeago: ^3.6.0
  timezone: ^0.10.1
  url_launcher: ^6.2.2
  uuid: ^4.2.2
  webview_flutter: ^4.7.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_facebook_auth: ^6.0.4
  flutter_cache_manager: ^3.3.1
  visibility_detector: ^0.4.0+2
  app_links: ^6.3.2 # uni_links yerine modern alternatif
  permission_handler: ^12.0.1
  wakelock_plus: ^1.1.4
  flutter_webrtc: ^0.14.2
  flutter_svg: ^2.0.9
  flutter_markdown: ^0.7.7+1
  webrtc_interface: ^1.1.1
  package_info_plus: ^8.3.0
  google_maps_flutter: ^2.5.3
  location: ^8.0.1
  geocoding: ^4.0.0
  geofence_flutter: ^2.0.0
  lottie: ^3.3.1
  flutter_animate: ^4.3.0
  # Güvenlik paketleri
  firebase_crashlytics: ^4.3.9
  mime: ^2.0.0
  flutter_image_compress: ^2.1.0
  rxdart: ^0.28.0
  # Video görüşme için gerekli paketler
  tflite_flutter: ^0.11.0
  envied: ^0.5.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  integration_test:
    sdk: flutter
  envied_generator: ^0.5.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/map_styles/
    - .env.prod

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_adaptive.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash_android12.png
    color: "#FFFFFF"
  fullscreen: true
